### ISSUE TITLE
orca

### ISSUE THREAD

**Issue by NilaBlueshirt** [ASU-KE/RC#11]
### Contact email

tpilaris@asu.edu

### ASURITE

tpilaris

### Software Name

orca

### Software version

5.0.3

### Cluster

Phoenix

**Comment by acchapm1** [comment]
testing ticket

**Comment by NilaBlueshirt** [comment]
Install the newest version 5.0.4 instead.

**Comment by NilaBlueshirt** [comment]
tutorial: https://www.orcasoftware.de/tutorials_orca/first_steps/install.html

Just go the the below page, download the all three parts

https://orcaforum.kofo.mpg.de/app.php/portal

Untar the three files, all contains executables

Move those files to the apps dir
