### ISSUE TITLE
itasca

### ISSUE THREAD

**Issue by NilaBlueshirt** [ASU-KE/RC#26]
### Contact email

ppaudya3@asu.edu

### ASURITE

ppaudya3

### Cluster

Sol

### Software Name

itasca

### Software version

Linux 7.00.161

### Link

https://www.itascainternational.com/software/downloads/itasca-linux-installer-7-0-update

### License

Yes

### Test Case

No

### Notes

User has license. TASK1139219.

**Comment by acchapm1** [comment]
built container and sent instructions how to use.
