### ISSUE TITLE
OpenFOAM

### ISSUE THREAD

**Issue by acchapm1** [ASU-KE/RC#6]
### Contact email

acchapm1@asu.edu

### ASURITE

acchapm1

### Software Name

OpenFOAM

### Software version

2312

### Notes

please install with openmpi on Sol

### Cluster

Sol

**Comment by acchapm1** [comment]
I have started building a container for this application.   When it's available I will send instructions how to use it.

**Comment by jlee562** [comment]
I also need this!!! PLEASE! Thank you!

**Comment by acchapm1** [comment]
closing as this is a test
